name: providerarchitecturetest
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  file_picker: ^5.3.2
  file_selector: ^1.0.0
  fl_chart: ^0.63.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  google_fonts: ^5.1.0
  uuid: ^3.0.7
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
